version: "3"

services:
  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  elasticsearch:
    container_name: es01
    image: elasticsearch:8.8.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ${HOME}/docker/elasticsearch:/data/elasticsearch
    environment:
      - discovery.type=single-node
      - ES_HOST=localhost
      - ES_PORT=9200
      - xpack.security.audit.enabled=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=password

  kibana:
    container_name: kib01
    image: kibana:8.8.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=password

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
